version: '2'
services:
    web:
        container_name: app_textransfer
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./public:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            default:
                aliases:
                    - local-app.textransfer.tech
            textransfer:
                aliases:
                    - local-app.textransfer.tech
networks:
    default:
        ipam:
            config:
                - subnet: 11.0.5.0/24
    textransfer:
        external: true
